adding detail page
1gr0k/RecipesList pull request #2
Opened 2021-07-29 13:00 UTC by 1gr0k

2021-08-13 09:25 UTC, Bleakcham requested changes

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Data/Network/APIEndpoints.swift
> +        return Endpoint(path: "recipeImages/\(path)-556x370.jpg",
вынести разрешения в enum (fullsize image, preview image) -> "556x37"

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Data/Network/DataMapping/RecipeDetailsRequestDTO+Mapping.swift
> +    let query: String
recipeId

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Data/PersistentStorages/RecepiesResponseStorage/EntityMapping/RecipeDetailResponseEntity+Mapping.swift
> +                     title: title!,
опциональные значения в базе не нужны?

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Data/PersistentStorages/RecepiesResponseStorage/EntityMapping/RecipeDetailResponseEntity+Mapping.swift
> +                     dishTypes: dishTypes?.allObjects.map { ($0 as! String) } ?? [],
посмотреть почему пришлось кастить

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Domain/Entities/DetailRecipe.swift
> +struct ExtIngredient: Equatable, Identifiable {
полные имена без сокращений

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/View/RecipeDetailsViewCell/RecipeDetailsHeaderViewCell.swift
> +        imagePath = imagePath.replacingOccurrences(of: " ", with: "-")
в модель

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/View/RecipeDetailsViewCell/RecipeDetailsTypesCollectionViewCell.swift
> +            let view = UIView()
отдельная функция для сабвью

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/View/RecipeDetailsViewController.swift
> +            return CGSize(width: view.frame.width - 16, height: view.frame.width / 556 * 370)
"магические числа" - константы...

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/ViewModel/RecipeDetailsViewModel.swift
> +    var recipe: Observable<RecipeDetailsCellViewModel?> { get }
dataSource = [sectionType: [CellViewModel]]

2021-08-13 09:25 UTC, Bleakcham commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/ViewModel/RecipeDetailsViewModel.swift
> +                self.recipe.value = RecipeDetailsCellViewModel(recipe: data)
дробление единой модели рецепта на модели ячеек

let headerModel = RecipeDetailHeaderCellViewModel(data)
let dishTypesModel = RecipeDetailDishTypesCellViewModel(data)
let ingridientsModels =data.extended.map { RecipeDetailIngridientCellViewModel(data) }
dataSource[.header] = [headerModel]
dataSource[.dishTypes] = [dishTypesModel]
dataSource[.ingridientsModels] = [ingridientsModels]

2021-08-13 09:52 UTC, 1gr0k commented on RecipesList/Data/Network/APIEndpoints.swift
> +        return Endpoint(path: "recipeImages/\(path)-556x370.jpg",
added enum RecipeImage Sizes, two function combined

2021-08-13 09:56 UTC, 1gr0k commented on RecipesList/Data/Network/DataMapping/RecipeDetailsRequestDTO+Mapping.swift
> +    let query: String
constant renamed

2021-08-13 10:12 UTC, 1gr0k commented on RecipesList/Data/PersistentStorages/RecepiesResponseStorage/EntityMapping/RecipeDetailResponseEntity+Mapping.swift
> +                     dishTypes: dishTypes?.allObjects.map { ($0 as! String) } ?? [],
возвращается массив [Any], кастить необходимо. force заменен на optional unwrapping с compactMap

2021-08-13 10:31 UTC, 1gr0k commented on RecipesList/Domain/Entities/DetailRecipe.swift
> +struct ExtIngredient: Equatable, Identifiable {
переименовано без сокращения

2021-08-13 10:41 UTC, 1gr0k commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/View/RecipeDetailsViewCell/RecipeDetailsHeaderViewCell.swift
> +        imagePath = imagePath.replacingOccurrences(of: " ", with: "-")
Преобразование имени ингредиента для пути изображения вынесено в отдельную переменную в модели, вычисляется там же

2021-08-13 10:51 UTC, 1gr0k commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/View/RecipeDetailsViewCell/RecipeDetailsTypesCollectionViewCell.swift
> +            let view = UIView()
генерация вынесена в setupDishTypeView

2021-08-13 11:14 UTC, 1gr0k commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/View/RecipeDetailsViewController.swift
> +            return CGSize(width: view.frame.width - 16, height: view.frame.width / 556 * 370)
соотношение сторон изображения вынесено в константу

2021-08-13 19:48 UTC, 1gr0k commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/ViewModel/RecipeDetailsViewModel.swift
> +    var recipe: Observable<RecipeDetailsCellViewModel?> { get }
общая модель разделена на секции в соответствии с внешним видом коллекции

2021-08-13 19:49 UTC, 1gr0k commented on RecipesList/Presentation/RecepiesScene/RecipeDetails/ViewModel/RecipeDetailsViewModel.swift
> +                self.recipe.value = RecipeDetailsCellViewModel(recipe: data)
модель разделена на несколько моделей в соответствии с секциями коллекции

2021-08-16 09:13 UTC, 1gr0k commented on RecipesList/Data/PersistentStorages/RecepiesResponseStorage/EntityMapping/RecipeDetailResponseEntity+Mapping.swift
> +                     title: title!,
CoreData по умолчанию отдает их как опционалы, чек-бокс у поля в базе имеет другой смысл, не как в swifte. выхода 2:
жестко создавать инициализировать вручную CoreDataProperties
извлечь опционал.
Решил извлечь опционал

2021-08-24 10:39 UTC, closed without merging